<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Command</code>
 */
class Command extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     */
    protected $deviceName = '';
    /**
     * "TURN_ON", "TURN_OFF", "SET_COLOR", "SET_STATE", etc
     *
     * Generated from protobuf field <code>string action = 2;</code>
     */
    protected $action = '';
    /**
     * "GREEN", "RED", "30C" (opcional)
     *
     * Generated from protobuf field <code>string value = 3;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $deviceName
     *     @type string $action
     *           "TURN_ON", "TURN_OFF", "SET_COLOR", "SET_STATE", etc
     *     @type string $value
     *           "GREEN", "RED", "30C" (opcional)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->deviceName;
    }

    /**
     * Generated from protobuf field <code>string deviceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceName = $var;

        return $this;
    }

    /**
     * "TURN_ON", "TURN_OFF", "SET_COLOR", "SET_STATE", etc
     *
     * Generated from protobuf field <code>string action = 2;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * "TURN_ON", "TURN_OFF", "SET_COLOR", "SET_STATE", etc
     *
     * Generated from protobuf field <code>string action = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * "GREEN", "RED", "30C" (opcional)
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * "GREEN", "RED", "30C" (opcional)
     *
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

