<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/messages.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DiscoveryRequest</code>
 */
class DiscoveryRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Messages::initOnce();
        parent::__construct($data);
    }

}

