<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/messages.proto

namespace GPBMetadata\Protobuf;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ü
protobuf/messages.proto"
DiscoveryRequest"X

DeviceInfo
name (	
type (	

ip (	
port (
currentState (	"=

SensorData

deviceName (	
type (	
value (	",
Command
	device_id (	
action (	"2
CommandResponse
status (	
message (	"*

DeviceList
devices (2.DeviceInfobproto3'
        , true);

        static::$is_initialized = true;
    }
}

