<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>DeviceList</code>
 */
class DeviceList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .DeviceInfo devices = 1;</code>
     */
    private $devices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \DeviceInfo[] $devices
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .DeviceInfo devices = 1;</code>
     * @return RepeatedField<\DeviceInfo>
     */
    public function getDevices()
    {
        return $this->devices;
    }

    /**
     * Generated from protobuf field <code>repeated .DeviceInfo devices = 1;</code>
     * @param \DeviceInfo[] $var
     * @return $this
     */
    public function setDevices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \DeviceInfo::class);
        $this->devices = $arr;

        return $this;
    }

}

